### ISSUE TITLE
*.less.d.ts

### ISSUE THREAD

**Issue by zlyzzy** [wanliyunyan/dva-typescript-antd-starter-kit#1]
这个文件好累赘啊 有办法less不使用ts么

**Comment by wanliyunyan** [comment]
@zhangly912 typescript 的项目就这样，需要大量的声明文件，目前我还不知道有什么办法不用，我也觉得累赘。。。

**Comment by zlyzzy** [comment]
哈喽，我发现一个好的办法，可以在根目录下面创建一个globals.d.ts 。。里面写上  
declare module "*.css" {
  const content: {
    [propName: string]: any
  };
  export default content;
}

declare module "*.less" {
  const content: {
    [propName: string]: any
  };
  export default content;
}

declare module "*.json" {
  const content: object;
  export default content;
}
这样去做，就不需要一个个去处理了。

**Comment by wanliyunyan** [comment]
@zhangly912 确实管用，还是你对技术理解的深
