### ISSUE TITLE
再请教一下，为什么react-hot-loader配置热替始终无效呢？

### ISSUE THREAD

**Issue by zlyzzy** [wanliyunyan/dva-typescript-antd-starter-kit#2]

**Comment by wanliyunyan** [comment]
@zhangly912 我这好使啊，这句话就是热加载
![image](https://user-images.githubusercontent.com/10751248/48610742-17609b80-e9c0-11e8-8587-3312ad881283.png)

**Comment by zlyzzy** [comment]
嗯是整个网页刷新 不是局部替换。。。然后我跟这个文章配置了一下react-hot-loader https://blog.csdn.net/huangpb123/article/details/78556652            .....然后发现redux部分的数据，局部热加载偶尔就会报错。

**Comment by wanliyunyan** [comment]
@zhangly912 https://github.com/gaearon/react-hot-loader/tree/master/examples/typescript 这是完整的例子，有时间我改下，谢谢

**Comment by wanliyunyan** [comment]
@zhangly912 我已经更新了，你可以参考我的配置，你发的那个有点过时了

**Comment by zlyzzy** [comment]
你这个热加载的配置我也试过，不过我这边的redux连接部分还是会报错，不知道跟我动态配置路由有木有关系。 不过不是很明白，为什么要把react-hot-loader放到dependencies，而不是原先的devDependencies。这个东西不是只需要开发的时候使用吗。为什么要放到打包依赖文件中呢？

**Comment by zlyzzy** [comment]
![image](https://user-images.githubusercontent.com/14969968/48767360-8fe19800-ecf1-11e8-9d86-ef7ae73b02e0.png)
![image](https://user-images.githubusercontent.com/14969968/48767391-9e2fb400-ecf1-11e8-8915-1f0202311f1e.png)

**Comment by zlyzzy** [comment]
![image](https://user-images.githubusercontent.com/14969968/48767446-bef80980-ecf1-11e8-8e8f-38d2257316dd.png)
因为不想文件都打包在一起，所以用了动态加载。。。心塞塞

**Comment by wanliyunyan** [comment]
我这个因为dva不支持ts的动态加载所以我就一次性都加载了，我也不知道你那为什么不好使，至于react-hot-loader在开发过程中引用了，就要放到dependencies中 @zhangly912
