### ISSUE TITLE
请问你解决了dva中项目使用react-hot-loader进行热替换吗？

### ISSUE THREAD

**Issue by ruralist-siyi** [wanliyunyan/dva-typescript-antd-starter-kit#3]
谢谢。

**Comment by wanliyunyan** [comment]
https://github.com/wanliyunyan/dva-typescript-antd-starter-kit/blob/master/src/index.tsx
开发模式动态引入 react-hot-loader/root
https://github.com/wanliyunyan/dva-typescript-antd-starter-kit/blob/master/babel.config.js
这个babel的配置

你在代码中搜索 react-hot-loader就可以看到了

**Comment by ruralist-siyi** [comment]
> https://github.com/wanliyunyan/dva-typescript-antd-starter-kit/blob/master/src/index.tsx
> 开发模式动态引入 react-hot-loader/root
> https://github.com/wanliyunyan/dva-typescript-antd-starter-kit/blob/master/babel.config.js
> 这个babel的配置
> 
> 你在代码中搜索 react-hot-loader就可以看到了

可以可以。非常感谢。我试一下。

**Comment by j78742** [comment]
通过dynamic引入的组件，渲染更新延后一次。

**Comment by wanliyunyan** [comment]
@j78742 你说这个项目，通过dynamic引入组件吗？

**Comment by j78742** [comment]
> @j78742 你说这个项目，通过dynamic引入组件吗？

是的，我尝试在dynamic之前包了一层hot，然后是可以的，但是每次都有警告
`hot(
  dynamic({
    app,
    models: () => models,
    component
  }));`

> Warning: You cannot change <Router history> 
    in Router (at app.js:17)
    in DvaRoot

**Comment by wanliyunyan** [comment]
@j78742 不好意思，我不太了解，之前在ts下尝试dynamic报错，后来就再没有使用dynamic
